transfermarkt_extract:
  scrapy_config:
    SPIDER_MODULES: ['transfermarkt']
    NEWSPIDER_MODULE: ['transfermarkt']
    USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'
    ROBOTSTXT_OBEY: true
    DOWNLOAD_DELAY: 1
    COOKIES_ENABLED: false
    REQUEST_FINGERPRINTER_IMPLEMENTATION: "2.7"
    TWISTED_REACTOR: "twisted.internet.asyncioreactor.AsyncioSelectorReactor"
    FEED_EXPORT_ENCODING: "utf-8"
    FEEDS:  # Configuration for feed exports
      'data/raw/%(name)s.json.gz':
        format: jsonlines
        overwrite: true  # Overwrite existing files
        encoding: utf-8
        postprocessing: 
          - scrapy.extensions.postprocessing.GzipPlugin  # Use Gzip for compression

