[tool.poetry]
name = "football-data-warehouse"
version = "0.1.0"
description = "Warehouse for football data from multiple sources"
authors = ["chonalchendo <110059232+chonalchendo@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scrapy = "^2.11.2"
football-data-extractor = {git = "https://github.com/chonalchendo/football-data-extractor.git", rev = "master"}
pyyaml = "^6.0.2"
dvc = {extras = ["gs"], version = "^3.55.2"}


[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^24.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
