
name: Build and Push Docker Image 

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          make docker-push-dockerhub 


