
name: Code linting and formatting

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install project
        run: poetry add black isort 
      #----------------------------------------------
      #              run linting
      #----------------------------------------------
      - name: Run isort
        run: poetry run isort . 

      - name: Run black
        run: poetry run black . 

      #----------------------------------------------
      #              commit linted files
      #----------------------------------------------
      - name: Commit linted files
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: '🤖 Apply code formatting'
          default_author: github_actions
          pull: '--no-rebase'
