name: Code linting and formatting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      #----------------------------------------------
      #       install black and isort
      #----------------------------------------------
      - name: Install black and isort
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      #----------------------------------------------
      #              run linting
      #----------------------------------------------
      - name: Run isort
        run: isort src/**/*.py orchestrator/**/*.py
      - name: Run black
        run: black src/**/*.py orchestrator/**/*.py
      #----------------------------------------------
      #              commit linted files
      #----------------------------------------------
      - name: Commit linted files
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.py'
          message: '🤖 Apply code formatting'
          default_author: github_actions
          pull: '--no-rebase'
