name: Test Scheduler for Dagster

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-dagster-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Dagster job
        run: uv run dagster job backfill -m foothouse.orchestrator -j github_actions_test_job --partitions 2024

